"""Agent: state, memory, decay, per-tick decision routing."""
from __future__ import annotations

import json
import os
import random
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from .config import CFG, effective_tick_health_drop, effective_tick_hunger_drop
from .logger import log


@dataclass
class House:
    id: str
    x: int
    y: int
    color: str
    style: str = "cottage"


@dataclass
class Agent:
    id: str
    name: str
    personality: str
    role: str = "worker"     # "worker" or "mentor"
    avatar: str = "🙂"
    house_id: Optional[str] = None
    # Stats
    health: float = float(CFG.max_health)
    hunger: float = float(CFG.max_hunger)
    alive: bool = True
    # Skill / mentorship
    skill_multiplier: float = 1.0       # transient mentorship boost
    skill_floor: float = 1.0            # earned-over-time base (drifts with experience)
    mentor_ticks: int = 0
    # Memory
    recent_actions: List[str] = field(default_factory=list)
    recent_outcomes: List[str] = field(default_factory=list)  # "win:+$21.30" / "loss:-$8.40"
    projects_built: int = 0
    reflections_written: int = 0
    knowledge_requests_sent: int = 0
    knowledge_requests_answered: int = 0
    # Bookkeeping
    born_at: float = field(default_factory=time.time)
    last_action: str = "idle"

    # ---- lifecycle ---------------------------------------------------------

    def decay(self) -> None:
        if not self.alive:
            return
        # Hunger always drops
        self.hunger = max(0.0, self.hunger - effective_tick_hunger_drop())
        # Health only drops at zero hunger
        if self.hunger <= 0.0:
            self.health = max(0.0, self.health - effective_tick_health_drop())
        # Mentorship wears off
        if self.mentor_ticks > 0:
            self.mentor_ticks -= 1
            if self.mentor_ticks == 0:
                self.skill_multiplier = 1.0
                log(self.id, "info", "mentorship boost faded")
        # Death
        if self.health <= 0.0:
            self.alive = False
            log(self.id, "death", f"{self.name} died (hunger {int(self.hunger)}%)")

    def feed(self, amount: int = CFG.food_restores_hunger) -> None:
        self.hunger = min(float(CFG.max_hunger), self.hunger + amount)

    def receive_mentorship(self, multiplier: float = 1.5, ticks: int = 8) -> None:
        self.skill_multiplier = max(self.skill_floor, multiplier)
        self.mentor_ticks = ticks

    def remember_action(self, label: str) -> None:
        self.recent_actions.append(label)
        if len(self.recent_actions) > 20:
            self.recent_actions = self.recent_actions[-20:]
        self.last_action = label

    def remember_outcome(self, label: str) -> None:
        self.recent_outcomes.append(label)
        if len(self.recent_outcomes) > 20:
            self.recent_outcomes = self.recent_outcomes[-20:]

    def nudge_skill(self, delta: float) -> None:
        """Slow drift of the skill floor — wins push up, losses push down."""
        self.skill_floor = max(0.7, min(1.6, self.skill_floor + delta))
        if self.mentor_ticks == 0:
            self.skill_multiplier = self.skill_floor

    def write_reflection(self, topic: str, text: str) -> None:
        self.reflections_written += 1
        self.append_memory(f"reflections-{topic}", text)

    # ---- memory (Obsidian-friendly) ----------------------------------------

    def memory_path(self) -> Path:
        p = Path(CFG.memory_dir) / self.id
        p.mkdir(parents=True, exist_ok=True)
        return p

    def append_memory(self, topic: str, text: str) -> None:
        try:
            f = self.memory_path() / f"{topic}.md"
            f.parent.mkdir(parents=True, exist_ok=True)
            with f.open("a", encoding="utf-8") as fp:
                fp.write(f"- {time.strftime('%Y-%m-%d %H:%M:%S')} — {text}\n")
        except OSError:
            pass

    def build_project(self, topic: str) -> Path:
        self.projects_built += 1
        safe_topic = "".join(c if c.isalnum() or c in "-_" else "-" for c in topic)[:64] or "untitled"
        folder = Path(CFG.projects_dir) / self.id
        folder.mkdir(parents=True, exist_ok=True)
        path = folder / f"{int(time.time())}-{safe_topic}.md"
        content = (
            f"# {topic}\n\n"
            f"_by {self.name} ({self.id}) — built {time.strftime('%Y-%m-%d %H:%M:%S')}_\n\n"
            f"Personality: {self.personality}\n\n"
            f"## Notes\n\n"
            f"This is a short artifact auto-generated by the agent.\n"
            f"Health at build: {int(self.health)}, Hunger: {int(self.hunger)}.\n"
            f"Skill multiplier: {self.skill_multiplier:.2f}.\n"
        )
        path.write_text(content, encoding="utf-8")
        return path

    # ---- serialization -----------------------------------------------------

    def public_state(self, economy_snapshot: dict) -> dict:
        money = economy_snapshot.get(self.id, {})
        return {
            "id": self.id,
            "name": self.name,
            "avatar": self.avatar,
            "personality": self.personality,
            "role": self.role,
            "house_id": self.house_id,
            "alive": self.alive,
            "health": round(self.health, 1),
            "hunger": round(self.hunger, 1),
            "skill_multiplier": round(self.skill_multiplier, 2),
            "skill_floor": round(self.skill_floor, 2),
            "mentor_ticks": self.mentor_ticks,
            "last_action": self.last_action,
            "projects_built": self.projects_built,
            "reflections_written": self.reflections_written,
            "knowledge_sent": self.knowledge_requests_sent,
            "knowledge_answered": self.knowledge_requests_answered,
            "cash": money.get("cash", 0),
            "earned": money.get("earned", 0),
            "real_usd": money.get("real_usd", 0.0),
            "meals": money.get("meals", 0),
        }
